version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: paksa_postgres
    environment:
      POSTGRES_DB: paksa_finance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - paksa_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: paksa_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - paksa_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: paksa_backend
    environment:
      - DATABASE_URI=postgresql+asyncpg://postgres:postgres@postgres:5432/paksa_finance
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=development
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/venv
    networks:
      - paksa_network
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: paksa_frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - paksa_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  paksa_network:
    driver: bridge